version: "3.3"
services:
  dev_db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=dev_db
    volumes:
      - ./gitignore/dev_db:/var/lib/postgresql/data
    ports:
      - 5443:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8078:8080
