# Generated by Django 4.2.5 on 2023-10-21 11:53

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('isFavorite', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('suburb', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=100)),
                ('max_num_of_guests', models.IntegerField()),
                ('price_per_night_for_one_guest', models.IntegerField()),
                ('price_per_night_per_extra_guest', models.IntegerField()),
                ('pictures', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bnb.picture')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
